apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default

  source:
    path: examples/argocd-kubevela/second-approach/apps
    repoURL: "https://github.com/GabrielBrotas/Learning-Journey/"
    targetRevision: HEAD

  destination:
    namespace: default
    server: "https://kubernetes.default.svc"

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
