site_name: Learning Journey
site_url: https://gabrielbrotas.github.io/Learning-Journey
repo_url: https://github.com/GabrielBrotas/Learning-Journey
edit_uri: blob/main/docs/
site_description: Sharing what I'm picking up along the way - exploring Architecture, DevOps, and Software Engineering
site_author: Gabriel Brotas
remote_branch: gh-deploy
nav:
  - Home: index.md
  - Architecture:
      - Types of Architecture: Architecture/types-of-architecture.md
      - Sustainability: Architecture/sustainability.md
      - Architectural Features: Architecture/architectural-features.md
      - Design Quality Software: Architecture/design-quality-software.md
  - AWS:
      - Regions and Availability Zones: AWS/1.regions-and-zones.md
      - IAM: AWS/2.iam.md
      - Budget And Cost: AWS/3.budget-and-cost.md
      - EC2 Fundamentals: AWS/4.ec2.md
      - EC2 Fundamentals Part 2: AWS/5.ec2-pt2.md
      - EC2 Storage: AWS/6.ec2-storage.md
  - Computer Science:
      - Program, Process and Thread: Computer-Science/core-thread-process.md
      - Object-Oriented-Programming vs Functional Programming: Computer-Science/OOP-vs-Functional-Programming.md
      - HTTPS, TLS and mTLS: Computer-Science/https-tls-mtls.md
      - Reactive Programming vs Reactive Systems: Computer-Science/reactive-programming-vs-reactive-systems.md
  - Domain Driven Design: domain-driven-design.md
  - GitOps: GitOps/index.md
  - IAM: IAM.md
  - Kafka:
      - Kafka/index.md
      - Topics: Kafka/topics.md
      - Producers and Consumers: Kafka/producers-and-consumers.md
      - Kafka Connect: Kafka/kafka-connect.md
      - Avro: Kafka/avro.md
  - Kubernetes: kubernetes.md
  - Microservices: microservices.md
  - Observability:
      - Observability/index.md
      - Service Level: Observability/service-level.md
      - OpenTelemetry: Observability/open-telemetry.md
      - Elastic Stack: Observability/elastic-stack.md
  - RabbitMQ: rabbitmq.md
  - Service Mesh:
      - ServiceMesh/index.md
      - Istio: ServiceMesh/istio.md
  - SOLID:
      - SOLID/index.md
      - Single Responsibility Principle: SOLID/single-responsability.md
      - Open-closed Principle: SOLID/open-closed.md
      - Liskov Substitution Principle: SOLID/liskov-substitution.md
      - Interface Segregation Principle: SOLID/interface-segregation.md
      - Dependency Inversion Principle: SOLID/dependency-inversion.md
  - Systems Communication:
      - SystemsCommunication/index.md
      - REST: SystemsCommunication/REST.md
      - gRPC: SystemsCommunication/gRPC.md
      - GraphQL: SystemsCommunication/GraphQL.md
theme:
  name: material
  logo: images/volcano.svg
  favicon: images/volcano.svg
  features:
    - tabs
    - content.tabs.link
    - content.code.copy
  font:
    code: Roboto Mono
    text: Roboto
  palette:
    - primary: black
      scheme: purple
      accent: red
plugins:
  - search:
      lang: en
  - glightbox
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
