site_name: Advanced Journey
site_url: https://gabrielbrotas.github.io/Advanced-Journey
repo_url: https://github.com/GabrielBrotas/Advanced-Journey
edit_uri: blob/main/docs/
site_description: My learning related to Architecture
site_author: Gabriel Brotas
remote_branch: gh-deploy
nav:
  - Home: index.md
  - Architecture:
      - Types of Architecture: Architecture/types-of-architecture.md
      - Sustainability: Architecture/sustainability.md
      - Architectural Features: Architecture/architectural-features.md
      - Design Quality Software: Architecture/design-quality-software.md
  - Systems Communication:
      - SystemsCommunication/index.md
      - REST: SystemsCommunication/REST.md
      - gRPC: SystemsCommunication/gRPC.md
      - GraphQL: SystemsCommunication/GraphQL.md
  - SOLID:
      - SOLID/index.md
      - Single Responsibility Principle: SOLID/single-responsability.md
      - Open-closed Principle: SOLID/open-closed.md
      - Liskov Substitution Principle: SOLID/liskov-substitution.md
      - Interface Segregation Principle: SOLID/interface-segregation.md
      - Dependency Inversion Principle: SOLID/dependency-inversion.md
  - Domain Driven Design: domain-driven-design.md
  - Microservices: microservices.md
  - Kafka:
    - Kafka/index.md
    - Topics: Kafka/topics.md
    - Producers and Consumers: Kafka/producers-and-consumers.md
    - Kafka Connect: Kafka/kafka-connect.md
    - Avro: Kafka/avro.md
  - RabbitMQ: rabbitmq.md
  - Kubernetes: kubernetes.md
  - Service Mesh: service-mesh.md
  - Observability:
    - Observability/index.md
    - Service Level: Observability/service-level.md
    - OpenTelemetry: Observability/open-telemetry.md
    - Elastic Stack: Observability/elastic-stack.md
  - Computer Science:
    - Program, Process and Thread: Computer-Science/core-thread-process.md
    - Object-Oriented-Programming vs Functional Programming: Computer-Science/OOP-vs-Functional-Programming.md
    - HTTPS, TLS and mTLS: Computer-Science/https-tls-mtls.md
    - Reactive Programming vs Reactive Systems: Computer-Science/reactive-programming-vs-reactive-systems.md
  - GitOps: GitOps/index.md
  - IAM: IAM.md
theme:
  name: material
  logo: images/volcano.svg
  favicon: images/volcano.svg
  features:
    - tabs
    - content.tabs.link
  font:
    code: Roboto Mono
    text: Roboto
  palette:
    - primary: black
      scheme: purple
      accent: red
plugins:
  - search:
      lang: en
  - glightbox
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
        permalink: True
