apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: examples/argocd-kubevela/apps
    repoURL: "https://github.com/GabrielBrotas/Advanced-Journey/"
    targetRevision: HEAD
    # plugin:
      # env:
      #   - name: APP_FILE_NAME
      #     value: app-oam.yml

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
