apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-b-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    id: tenant-b
spec:
  description: Project for Tenant B
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
      name: in-cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceNamespaces:
    - "tenant-b-dev"
