apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-a-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    id: tenant-a
spec:
  description: Project for Tenant A
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
      name: in-cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceNamespaces:
    - "tenant-a-dev"
