apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-repo-project-binding
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: check-repo-for-project
      match:
        resources:
          kinds:
            - argoproj.io/v1alpha1/Application
          selector:
            matchLabels:
              argocd.argoproj.io/instance: tenant-a-dev_tenant-a.dev.app-of-apps
      validate:
        message: "This repository is not allowed to deploy to the specified project."
        deny:
          conditions:
            - key: "{{ request.object.spec.project }}"
              operator: NotEquals
              value: "tenant-a-dev"
