argo-cd:
  applicationSet:
    enabled: false
  dex:
    enabled: false

  repoServer:
    clusterAdminAccess:
      enabled: true

    extraContainers:
      - name: vela
        image: nginx
        command: [/var/run/argocd/argocd-cmp-server]
        # env:
        #   - name: KUBECONFIG
        #     value: /kubeconfig
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - name: var-files
            mountPath: /var/run/argocd
          - name: vela-cli-dir
            mountPath: /.vela
          # - name: kubeconfig
          #   mountPath: /kubeconfig
          #   subPath: kubeconfig
          - name: plugins
            mountPath: /home/argocd/cmp-server/plugins
          - name: vela-cmp
            mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: plugin.yaml
          - name: cmp-tmp
            mountPath: /tmp
          - name: custom-tools
            mountPath: /usr/local/bin/vela
            subPath: vela

    initContainers:
      - name: kubevela
        image: nginx:1.21.6
        command:
          - bash
          - "-c"
          - |
            #!/usr/bin/env bash
            set -eo pipefail
            curl -fsSl https://kubevela.io/script/install.sh | bash -s 1.6.4
        env:
          - name: VELA_INSTALL_DIR
            value: /custom-tools
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
        volumeMounts:
          - name: custom-tools
            mountPath: /custom-tools
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent

    volumes:
      - emptyDir: {}
        name: custom-tools
      - configMap:
          name: vela-cmp
        name: vela-cmp
      - emptyDir: {}
        name: cmp-tmp
      - emptyDir: {}
        name: vela-cli-dir
