# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: vela-cmp
#   namespace: argocd
# data:
#   plugin.yaml: |
#     apiVersion: argoproj.io/v1alpha1
#     kind: ConfigManagementPlugin
#     metadata:
#       name: vela
#     spec:
#       version: v1.0
#       init:
#         command: ["vela", "traits"]
#       generate:
#         command: ["sh"]
#         args:
#           - -c
#           - |
#             vela export -f "${APPFILE_PATH}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-cmp
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: vela
    spec:
      version: v1.0
      init:
        command: ["vela", "traits"]
      generate:
        command: ["sh"]
        args:
          - -c
          - |
            vela dry-run -f test-argo-oam.yml
      discover:
        # fileName: "-oam.yml*"
        find:
          # This does the same thing as fileName, but it supports double-start (nested directory) glob patterns.
          glob: "**/*oam*.yml"
