##################################################################################################
# NGIXN Service
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: nginx
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-vs
spec:
  hosts:
    - "*" # k8s nginx service
  gateways:
    - nginx-gateway
  http:
    - match:
        - uri:
            exact: "/"
      route:
        - destination:
            host: nginx
            subset: all
          weight: 100 # consistentHash doesn't work with different weight
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: nginx-dr
spec:
  host: nginx
  trafficPolicy: # traffic policy for load balancing:
    loadBalancer: # load balancing policy is
      consistentHash: # consistentHash
        httpHeaderName: "x-user" # generate hash based on x-user header
  subsets:
    - name: all
      labels:
        app: nginx
