name: gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "requirements.txt"
      - ".github/workflows/gh-pages.yml"

permissions:
  pages: write
  contents: write

jobs:
  deploy:
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Add Google Analytics
        run: |
          echo "extra:" >> mkdocs.yml
          echo "  analytics:" >> mkdocs.yml
          echo "    provider: google" >> mkdocs.yml
          echo "    property: ${{ secrets.GA_PROPERTY }}" >> mkdocs.yml

      - name: Build site
        run: |
          mkdocs build --verbose --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./site
          publish_branch: gh-pages
          force_orphan: true
