apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
  namespace: default
spec:
  components:
    - name: express-server
      type: com.wexinc.webservice
      properties:
        image: oamdev/hello-world
        namespace: app-1
        project: fabric-dev
        ports:
          - port: 8000
            expose: true
      # traits:
      #   - type: scaler
      #     properties:
      #       replicas: 1
      # - type: argo-app-trait
      #   properties:
      #     name: first-vela-app
